### ISSUE TITLE
Setting Lock state results in a 503 error

### ISSUE THREAD

**Issue by davidnoyes** [gndean/home-assistant-hypervolt-charger#15]
Build v1.0.6-beta

Changing the lock state results in HA prompting "Failed to call service switch/turn_on(off)".

The HA logs give the following:
```
Logger: custom_components.hypervolt_charger.hypervolt_api_client
Source: custom_components/hypervolt_charger/hypervolt_api_client.py:530 
Integration: Hypervolt Charger ([documentation](https://github.com/gndean/home-assistant-hypervolt-charger), [issues](https://github.com/gndean/home-assistant-hypervolt-charger/issues)) 
First occurred: 10:41:28 (6 occurrences) 
Last logged: 11:00:45

Set lock status, error from API, status: 503
```

and

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/hypervolt_charger/hypervolt_api_client.py:534 
Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22)) 
First occurred: 10:41:28 (6 occurrences) 
Last logged: 11:00:45

[140374751470320]
[140373852643648]
[140373518298336]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/config/custom_components/hypervolt_charger/switch.py", line 62, in async_turn_on
    await self._hypervolt_coordinator.api.set_lock_state(
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 534, in set_lock_state
    raise CannotConnect
custom_components.hypervolt_charger.hypervolt_api_client.CannotConnect
```

All other functions are working as expected.

Changing the lock status in the app results in the switch state changing as expected.

**Comment by gndean** [comment]
Thanks for the report - acknowledging. At the moment, I can't think why this would happen though 🤔 

Just checking you have a Hypervolt 2.0 version charger?

**Comment by davidnoyes** [comment]
Ah sorry I should have posted that up front. It's actually v3.

Home Charger 3.0
Firmware version: 1504.0

**Comment by gndean** [comment]
Maaaaybe the version 3.0 charger uses a different API for the lock feature?

If you go to https://dashboard.hypervolt.co.uk/ , can you see a lock feature within the web UI? (I can't with my 2.0 charger, just wondered if it was different for you).

**Comment by davidnoyes** [comment]
No sadly not, the dashboard has very few features.

**Comment by gndean** [comment]
It looks like a new API is being used and enforced for Hypervolt Home 3.0 users.
I've made a V1.0.9 release that should hopefully resolve this.
Let me know if it works for you.

**Comment by davidnoyes** [comment]
💥 Working perfectly!

**Comment by davidnoyes** [comment]
Thanks for the help

**Comment by davidnoyes** [comment]
For intrigue and future reference, how did you discover that it had changed from a POST to a websocket message?

**Comment by gndean** [comment]
* Taps nose *
It's how the latest build of the Hypervolt mobile app works. Previous versions, and what I based the integration on, made the POST request.

**Comment by davidnoyes** [comment]
😉 gotcha.

**Comment by garethbradley** [comment]
Working a treat - thanks so much for your hard work. I tried to help by routing my phone data through HTTPToolkit but alas, it wouldn't even connect with the Hypervolt app!
