### ISSUE TITLE
Error In Logs

### ISSUE THREAD

**Issue by Evaske** [gndean/home-assistant-hypervolt-charger#41]
Hello,

I am seeing a repeating error in my logs related to the Hypervolt plugin. Seems to occur every 5 minutes. 

```
2024-01-27 13:31:19.233 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 243, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 399, in _async_refresh
    self.async_update_listeners()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 182, in async_update_listeners
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 479, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 945, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1066, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1003, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 951, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/time/__init__.py", line 101, in state
    if self.native_value is None:
       ^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hypervolt_charger/time.py", line 63, in native_value
    if len(intervals) > self.interval_index and intervals[self.interval_index]:
       ^^^^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()
2024-01-27 13:31:19.243 WARNING (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] On_sync_websocket_message_callback error $object of type 'NoneType' has no len()
2024-01-27 13:31:19.251 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] on_session_in_progress_websocket_message_callback message: {"charging":false,"session":214,"milli_amps":32000,"true_milli_amps":0,"watt_hours":0,"ccy_spent":0,"carbon_saved_grams":0,"ct_current":0,"ct_power":0,"voltage":0}, error: object of type 'NoneType' has no len()
```

**Comment by gndean** [comment]
Thanks for reporting. This should now be fixed in V2.0.2
