### ISSUE TITLE
v2.2.6 misbehaving on HASS restart, incorrectly changes to Plug and Charge

### ISSUE THREAD

**Issue by pdcastro** [gndean/home-assistant-hypervolt-charger#58]
**Versions**

* Integration v2.2.6
* HASS Core version 2024.6.2, Frontend version 20240610.0
* Hypervolt Home 2 charger

**Pre-conditions**

* Disable any automations that interact with this integration.
* Upgrade the integration from v2.2.2 to v2.2.6 through HACS.
* Restart HASS.

*Scenario 1:*

1. Start from a state where the Hypervolt charger (Home 2), the official Android app and this integration are all in agreement for scheduled charging, for example a single session from 11am to 12pm.
2. Restart HASS.
3. After the frontend advises that HASS has finished starting, reload the frontend web page (to be sure that all state is loaded fresh) and note how the frontend unexpectedly shows this integration’s entities with blank fields for “Hypervolt Activation Mode” and the scheduled sessions, as shown on the screenshot below. (With v2.2.2 and earlier, the dropdown shows “Schedule” rather than being blank. The v2.2.2 behaviour is what I consider to be correct.)
4. Attempt to change the “Hypervolt Activation Mode” dropdown from “blank”  to “Schedule”.
5. Observe how this causes a stack trace error on the HASS logs: `TypeError: 'NoneType' object is not iterable`. See Logs section below.
6. Note how the “Hypervolt Activation Mode” dropdown selection changes ***by itself*** from “Schedule” to “Plug and Charge”, and the car starts charging straight away (incorrect and undesired behavior, as scheduled charging is intended).

*Scenario 2:*

1. Same as Scenario 1
2. Same as Scenario 1
3. Same as Scenario 1
4. Enter for example 11:00 and 12:00 in the Hypervolt Schedule Session 1 Start Time and End Time fields respectively. Press the Hypervolt Apply Schedule button.
5. Unlike Scenario 1, observe that no errors are shown in the logs.
6. Like Scenario 1, note how the “Hypervolt Activation Mode” dropdown selection changes ***by itself*** from “Schedule” to “Plug and Charge”, and the car starts charging (incorrect and undesired behavior, as scheduled charging is intended).

*Scenario 3:*

Enable HASS automations that change the charging schedule through this integration (automations that were disabled while testing Scenario 1 and Scenario 2 above). Observe how the automations fail to change the charging schedule on HASS restart. These automations used to work well with the Hypervolt integration version 2.2.2 and earlier. I believe it is because of the same issue behind Scenarios 1 and 2.

**Additional info**

I also tried deleting and re-adding the Hypervolt device through HASS Settings -> Devices & Services -> Hypervolt Charger -> Three-vertical-dot icon next to the Hypervolt device -> Delete, then clicking Add Device and entering the Hypervolt email address and password. It did not make a difference.

**Screenshots**

![Screenshot 2024-06-23 at 21 30 56](https://github.com/gndean/home-assistant-hypervolt-charger/assets/15091591/732c8805-663e-4b89-aa94-dcb3a4865e65)

**Logs**

```logs
2024-06-23 21:04:49.067 DEBUG (MainThread) [custom_components.hypervolt_charger] Async_setup enter
2024-06-23 21:04:49.067 DEBUG (MainThread) [custom_components.hypervolt_charger] Async_setup_entry enter, entry_id: de78728955cadb8a918551d5f75680b8
2024-06-23 21:04:49.067 DEBUG (MainThread) [custom_components.hypervolt_charger.utils] get_version_from_manifest loading manifest: /config/custom_components/hypervolt_charger/manifest.json
2024-06-23 21:04:49.094 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to open inside the event loop by custom integration 'hypervolt_charger' at custom_components/hypervolt_charger/utils.py, line 17: with open(manifest_filename, encoding="utf-8") as manifest_file: (offender: /config/custom_components/hypervolt_charger/utils.py, line 17: with open(manifest_filename, encoding="utf-8") as manifest_file:), please create a bug report at https://github.com/gndean/home-assistant-hypervolt-charger/issues
2024-06-23 21:04:49.096 DEBUG (MainThread) [custom_components.hypervolt_charger.utils] get_version_from_manifest returning version: 2.2.6
2024-06-23 21:04:49.096 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Create_hypervolt_coordinator enter
2024-06-23 21:04:49.097 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Create_hypervolt_coordinator HypervoltApiClient created, charger_id: [deleted]
2024-06-23 21:04:49.097 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] HypervoltUpdateCoordinator init
2024-06-23 21:04:49.097 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Create_hypervolt_coordinator HypervoltUpdateCoordinator created
2024-06-23 21:04:49.098 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Hypervolt _update_with_fallback enter, retry = True
2024-06-23 21:04:49.098 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] No active session
2024-06-23 21:04:49.098 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] HypervoltCoordinator _update_with_fallback, retry = True, exception:
2024-06-23 21:04:49.098 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Attempting log in
2024-06-23 21:04:49.408 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] HypervoltApiClient logged in!
2024-06-23 21:04:49.409 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Hypervolt _update_with_fallback enter, retry = False
2024-06-23 21:04:49.409 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] No active session
2024-06-23 21:04:49.409 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] HypervoltCoordinator _update_with_fallback, retry = False, exception:
2024-06-23 21:04:49.410 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] HypervoltCoordinator _update_with_fallback, retry = False, returning self.data
2024-06-23 21:04:49.410 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Finished fetching hypervolt_charger data in 0.312 seconds (success: True)
2024-06-23 21:04:49.410 DEBUG (MainThread) [custom_components.hypervolt_charger] Async_setup_entry async_forward_entry_setups
2024-06-23 21:04:49.411 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, enter
2024-06-23 21:04:49.493 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket session/in-progress, Task-1512, enter
2024-06-23 21:04:49.668 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, connected
2024-06-23 21:04:49.668 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync: {"id": "1719176689668764", "method": "login", "params": {"token": "********", "version": 2}, "jsonrpc": "2.0"}
2024-06-23 21:04:49.689 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket session/in-progress, Task-1512, connected
2024-06-23 21:04:49.698 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, recv: {"jsonrpc":"2.0","id":"1719176689668764","result":{"authenticated":true}}
2024-06-23 21:04:49.699 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync: {"id": "1719176689698874", "method": "sync.snapshot", "jsonrpc": "2.0"}
2024-06-23 21:04:50.203 DEBUG (MainThread) [custom_components.hypervolt_charger.switch] Switch async_setup_entry enter
2024-06-23 21:04:50.212 DEBUG (MainThread) [custom_components.hypervolt_charger.time] Time async_setup_entry enter
2024-06-23 21:04:50.221 DEBUG (MainThread) [custom_components.hypervolt_charger.button] Button async_setup_entry enter
2024-06-23 21:04:50.227 DEBUG (MainThread) [custom_components.hypervolt_charger.text] Text async_setup_entry enter
2024-06-23 21:04:50.228 DEBUG (MainThread) [custom_components.hypervolt_charger.binary_sensor] Binary Sensor async_setup_entry enter
2024-06-23 21:04:50.228 DEBUG (MainThread) [custom_components.hypervolt_charger] Async_setup_entry async_forward_entry_setups done
2024-06-23 21:04:51.490 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, recv: {"jsonrpc":"2.0","id":"1719176689698874","result":[{"brightness":0.0},{"lock_state":"unlocked"},{"release_state":"default"},{"max_current":6000},{"ct_flags":1},{"solar_mode":"boost"},{"features":["super_eco","christmas_mode","regs2022"]},{"random_start":false}]}
2024-06-23 21:04:51.490 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Manually updated hypervolt_charger data
2024-06-23 21:04:51.946 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, recv: {"jsonrpc":"2.0","method":"get.pilot_status","params":{"pilot_status":"A"}}
2024-06-23 21:04:51.947 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Manually updated hypervolt_charger data
2024-06-23 21:04:51.963 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-1511, recv: {"jsonrpc":"2.0","method":"get.session","params":{"charging":false,"true_milli_amps":0,"voltage":0,"watt_hours":52,"carbon_saved_grams":22,"ct_current":0,"ev_power":0,"grid_power":0,"house_power":0,"generation_power":0}}
2024-06-23 21:04:51.963 DEBUG (MainThread) [custom_components.hypervolt_charger.hypervolt_update_coordinator] Manually updated hypervolt_charger data
2024-06-23 21:05:10.795 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [133017465339424] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 241, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 191, in async_handle_select_option
    await self.async_select_option(option)
  File "/config/custom_components/hypervolt_charger/select.py", line 165, in async_select_option
    await self._hypervolt_coordinator.api.set_schedule(
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 687, in set_schedule
    for schedule_interval in schedule_intervals:
TypeError: 'NoneType' object is not iterable
```

**Comment by gndean** [comment]
Thanks for the detailed report. This should now be fixed in V2.3.0
