### ISSUE TITLE
AttributeError: TIME

### ISSUE THREAD

**Issue by scrauny** [gndean/home-assistant-hypervolt-charger#59]
Started receiving the below error, possibly after a Home Assistant restart. Restarting doesn't work.
Upgraded to v2.2.6 but issue persists.
Everything worked fine before. It is not possible to remove the integration and re-add.

custom_components/hypervolt_charger/time.py does exist.

Thanks for any pointers :-) 

`This error originated from a custom integration.

Logger: homeassistant.loader
Source: custom_components/hypervolt_charger/__init__.py:22
Integration: Hypervolt Charger (documentation, issues)
First occurred: 15:41:35 (1 occurrences)
Last logged: 15:41:35

Unexpected exception importing component custom_components.hypervolt_charger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 725, in get_component
    cache[self.domain] = importlib.import_module(self.pkg_path)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/hypervolt_charger/__init__.py", line 22, in <module>
    Platform.TIME,
  File "/usr/local/lib/python3.10/enum.py", line 437, in __getattr__
    raise AttributeError(name) from None
AttributeError: TIME
`

**Comment by graham-dean-rm** [comment]
What version of Home Assistant are you running? Could it be an old (pre-2024) version?

**Comment by gndean** [comment]
What version of Home Assistant are you running? Could it be an old (pre-2024) version?

**Comment by scrauny** [comment]
> What version of Home Assistant are you running? Could it be an old (pre-2024) version?

It was a 2023 version, pulling a new container with the latest Home Assistant version fixed the issue.
Many thanks.
