### ISSUE TITLE
No device or entities

### ISSUE THREAD

**Issue by crobbins215d** [gndean/home-assistant-hypervolt-charger#6]
No device or entities loaded, when set up yesterday I assumed it might just take a while to load or need a charge sync on the car that I did last night.

![hyper](https://user-images.githubusercontent.com/44638417/208079496-565134d6-01f4-442c-b3ae-b7eafb1ad19d.png)

The serial number for the device has been loaded and matches my charger in the app.

![Screenshot_20221216-100038](https://user-images.githubusercontent.com/44638417/208078462-17825fb5-9390-45ac-a35a-6b785ce03a7e.png)

I only have 1 charger.

Reloaded Hypervolt this morning following password change to see if it would load

Logs
[error_log-2.txt](https://github.com/gndean/home-assistant-hypervolt-charger/files/10244908/error_log-2.txt)

Any idea or suggestions for me to try?

**Comment by crobbins215d** [comment]
I'm on 
homeassistant 2022.12.6
Supervisor 2022.11.2
Operating System 9.4

**Comment by joshcliffejones** [comment]
I have the same issue having just added the integration last night only for it to succeed in adding to HA, but pulling through no devices or entities :(

**Comment by gndean** [comment]
I'm not sure what's happening here. Maybe the start up occurs in a different order, or some step is missing from what I expect.
Thanks for the logs - that's helpful. Would you be able to capture again with:
1) The 1.0.2 release as this adds some more logging, and
2) Debug log level enabled for the integration. So this adding to your configuration.yaml:
```
logger:
  default: warning
  logs:
    custom_components.hypervolt_charger: debug
```

Thanks!

**Comment by joshcliffejones** [comment]
Many thanks for your help @gndean

Ive updated and dumped out a snippet of the debug log!

2022-12-17 19:22:18.292 WARNING (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Update_state_from_schedule, unauthorised
2022-12-17 19:22:20.173 ERROR (MainThread) [homeassistant.components.switch] Error adding entities for domain switch with platform hypervolt_charger
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/hypervolt_charger/switch.py", line 44, in unique_id
    return super().unique_id + "_charging"
  File "/config/custom_components/hypervolt_charger/hypervolt_entity.py", line 33, in unique_id
    return self.coordinator.data.charger_id
AttributeError: 'NoneType' object has no attribute 'charger_id'
2022-12-17 19:22:20.192 ERROR (MainThread) [homeassistant.components.switch] Error while setting up hypervolt_charger platform for switch
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 289, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 428, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 503, in _async_add_entity
    if entity.unique_id is not None:
  File "/config/custom_components/hypervolt_charger/switch.py", line 44, in unique_id
    return super().unique_id + "_charging"
  File "/config/custom_components/hypervolt_charger/hypervolt_entity.py", line 33, in unique_id
    return self.coordinator.data.charger_id
AttributeError: 'NoneType' object has no attribute 'charger_id'
2022-12-17 19:22:20.316 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Notify_on_hypervolt_session_in_progress_push error: 'NoneType' object has no attribute 'is_charging'
2022-12-17 19:22:20.326 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_hypervolt_sync_push error: 'NoneType' object has no attribute 'led_brightness'
2022-12-17 19:22:20.331 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up hypervolt_charger platform for sensor
Traceback (most recent call last):
  File "/config/custom_components/hypervolt_charger/hypervolt_update_coordinator.py", line 78, in _update_with_fallback
    state = await self.api.update_state_from_schedule(
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 139, in update_state_from_schedule
    state.activation_mode = HypervoltActivationMode.PLUG_AND_CHARGE
AttributeError: 'NoneType' object has no attribute 'activation_mode'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 49, in login
    async with session.get("https://api.hypervolt.co.uk/login-url") as response:
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.10/site-packages/aiohttp/connector.py", line 545, in connect
    raise ClientConnectionError("Connector is closed.")
aiohttp.client_exceptions.ClientConnectionError: Connector is closed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/config/custom_components/hypervolt_charger/hypervolt_update_coordinator.py", line 71, in _async_update_data
    return await self._update_with_fallback()
  File "/config/custom_components/hypervolt_charger/hypervolt_update_coordinator.py", line 95, in _update_with_fallback
    await self.api.login(self.api_session)
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 103, in login
    raise CannotConnect from exc
custom_components.hypervolt_charger.hypervolt_api_client.CannotConnect

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/hypervolt_charger/hypervolt_update_coordinator.py", line 73, in _async_update_data
    raise UpdateFailed() from exception
homeassistant.helpers.update_coordinator.UpdateFailed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/hypervolt_charger/sensor.py", line 38, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 197, in async_config_entry_first_refresh
    raise ex
homeassistant.exceptions.ConfigEntryNotReady

**Comment by gndean** [comment]
Thanks @joshcliffejones, that looks like the same type of error as @crobbins215d 
Any chance of repeating after having changed the logger level for the integration using the snippet in https://github.com/gndean/home-assistant-hypervolt-charger/issues/6#issuecomment-1356330679?
There should be more lines logged once the logger level is changed.

**Comment by crobbins215** [comment]
Updated.

Added 
logger:
  default: warning
  logs:
    custom_components.hypervolt_charger: debug
    
Restarted, cleared log. Reloaded hypervolt 

Logs attached
[home-assistant_2022-12-18T16-56-18.833Z.log](https://github.com/gndean/home-assistant-hypervolt-charger/files/10254282/home-assistant_2022-12-18T16-56-18.833Z.log)

**Comment by gndean** [comment]
Thanks - investigating 👀

**Comment by joshcliffejones** [comment]
> Thanks @joshcliffejones, that looks like the same type of error as @crobbins215d Any chance of repeating after having changed the logger level for the integration using the snippet in [#6 (comment)](https://github.com/gndean/home-assistant-hypervolt-charger/issues/6#issuecomment-1356330679)? There should be more lines logged once the logger level is changed.

Many thanks! I added the logger level entry and have attached the logs

[home-assistant_hypervolt_charger_2022-12-18T22-41-09.232Z.log](https://github.com/gndean/home-assistant-hypervolt-charger/files/10254841/home-assistant_hypervolt_charger_2022-12-18T22-41-09.232Z.log)

**Comment by gndean** [comment]
OK, I've created V1.0.3 with some slight changes to the initialisation logic and some extra debug logging. Give it a go and if still no joy, can you attach some logs again. Thanks!

**Comment by crobbins215** [comment]
Amazing work @gndean , thats got mine working, thank you for sorting

![image](https://user-images.githubusercontent.com/10505316/208530502-e1b1e2f1-2a20-436a-9aa4-0b6ac22487c2.png)

Side note and unrelated but the title doesn't have a logo icon, that's just a FYI, isn't an issue 
![image](https://user-images.githubusercontent.com/10505316/208530794-87534c74-7912-4f09-bcb2-56155f321984.png)

Thank you again!!!

**Comment by gndean** [comment]
Great news 🎉  Thanks for the feedback.
An icon should be arriving soon. For that, I've had to submit images to this global repository and that's only just accepted today, so hopefully HACS / HA should update soon: https://github.com/home-assistant/brands

**Comment by crobbins215** [comment]
🎉

**Comment by joshcliffejones** [comment]
> OK, I've created V1.0.3 with some slight changes to the initialisation logic and some extra debug logging. Give it a go and if still no joy, can you attach some logs again. Thanks!

I can confirm mine is now working too! 👍 Superb work @gndean and a swift fix at that!

**Comment by gndean** [comment]
Great 🎉 Thanks for confirming
