### ISSUE TITLE
HASS warning: Detected blocking call to 'open' inside the event loop by custom integration 'hypervolt_charger'

### ISSUE THREAD

**Issue by pdcastro** [gndean/home-assistant-hypervolt-charger#60]
* Hypervolt integration v2.3.0
* HASS Core version 2024.6.4
* Logs when HASS starts:

```
2024-06-29 22:53:41.926 WARNING (MainThread) [homeassistant.util.loop] 
  Detected blocking call to open inside the event loop by custom integration 'hypervolt_charger'
  at custom_components/hypervolt_charger/utils.py, line 17:
    with open(manifest_filename, encoding="utf-8") as manifest_file:
  (offender: /config/custom_components/hypervolt_charger/utils.py, line 17:
    with open(manifest_filename, encoding="utf-8") as manifest_file:),
  please create a bug report at https://github.com/gndean/home-assistant-hypervolt-charger/issues
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 165, in async_setup_component
    result = await _async_setup_component(hass, domain, config)
  File "/usr/src/homeassistant/homeassistant/setup.py", line 447, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/setup.py", line 449, in <genexpr>
    create_eager_task(
  File "/usr/src/homeassistant/homeassistant/util/async_.py", line 37, in create_eager_task
    return Task(coro, loop=loop, name=name, eager_start=True)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
    await self.async_setup(hass, integration=integration)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/hypervolt_charger/__init__.py", line 53, in async_setup_entry
    get_version_from_manifest(),
  File "/config/custom_components/hypervolt_charger/utils.py", line 17, in get_version_from_manifest
    with open(manifest_filename, encoding="utf-8") as manifest_file:
```

I understand that the `open` call relates to simply reading a small file (`json.load(manifest_file)`) and it is therefore fairly harmless, however the stack trace in the HASS logs does not look good to end users, and synchronous I/O is not good form within HASS. HASS dev docs suggest that the solution is to run the `open` ***and*** `json.load` calls _(“all the blocking reads and writes must also be fixed”)_ through an `asyncio` executor (i.e., in a separate thread handled by `asyncio`):
https://developers.home-assistant.io/docs/asyncio_blocking_operations/#open

**Comment by gndean** [comment]
Thanks for the detailed report.
This should be fixed in [V2.3.1](https://github.com/gndean/home-assistant-hypervolt-charger/releases/tag/v2.3.1) now
