### ISSUE TITLE
Several minutes delay to synchronise the schedule following a token refresh

### ISSUE THREAD

**Issue by pdcastro** [gndean/home-assistant-hypervolt-charger#63]
Versions:
* Hypervolt Home charger v2
* Hypervolt integration v2.3.0
* HASS Core version 2024.6.4

I understand that the authentication token needs to be refreshed from time to time, and that is what the logs below are showing. Apart from the stack trace error (if `InvalidAuth` is an expected condition that triggers a token refresh, it shouldn’t be logged as an error), the logged behaviour seems OK:
```
2024-07-04 16:14:56.795 INFO (MainThread) [custom_components.hypervolt_charger.button] Apply Schedule button pressed
2024-07-04 16:14:56.795 INFO (MainThread) [custom_components.hypervolt_charger.button] Setting 1 schedule intervals
2024-07-04 16:14:56.818 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-264433, iterator exited. Socket closed, code: 1000, reason: Bye
2024-07-04 16:14:56.959 WARNING (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Set_schedule, unauthorised
2024-07-04 16:14:56.960 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall button.press (c:01J1Z8E1RBJGGP8EBTXKSTWTHF): entity_id=['button.hypervolt_apply_schedule']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 2761, in _run_service_call_catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 977, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1049, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/button/__init__.py", line 134, in _async_press_action
    await self.async_press()
  File "/config/custom_components/hypervolt_charger/button.py", line 54, in async_press
    await self._hypervolt_coordinator.api.set_schedule(
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 722, in set_schedule
    raise InvalidAuth
custom_components.hypervolt_charger.hypervolt_api_client.InvalidAuth
2024-07-04 16:15:00.819 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Attempting to refresh access token
2024-07-04 16:15:00.970 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Access token refreshed
2024-07-04 16:15:01.106 INFO (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-264433, connected
```

The issue is that I observed a period of approximately 6 minutes during which the Hypervolt integration entity values were out of sync with the cloud, following a token refresh. I believe that the sequence of events was:

1- Hypervolt Schedule Session 1 Start Time had value ’10:00’.
2- Its value was locally changed from ’10:00’ to ’11:00’ and Apply Schedule was pressed (through an automation rather than a person, but it should not matter).
3- An `InvalidAuth` error happened and the new schedule value (11:00) was *not* propagated to the cloud.
4- A token refresh was successfully performed (as a result of the `InvalidAuth` error).
5- Hypervolt Schedule Session 1 Start Time had value ’11:00’ locally, but in the cloud it still had value ’10:00’.
6- Some 6 minutes later, Hypervolt Schedule Session 1 Start Time changed locally from ’11:00’ to ’10:00’, getting in sync with the cloud but losing the value change attempted in step 2.

If it helps to clarify further:
I have an automation that runs every 1 minute and compares the “current state” of the charging schedule (as reported by the Hypervolt integration entities) with the “target state” desired by the automation. If the current and target states match, the work is done. If the states differ, my automation sets the target values on the entities (Hypervolt Schedule Session 1 Start Time, End Time) and calls the button press service on the Apply Schedule button. For about 6 minutes, the Hypervolt integration entities were reporting the desired target state and therefore there was nothing to do. Suddenly, the Hypervolt integration entities reported old schedule values that were supposed to have been changed ~6 minutes earlier (when a token refresh took place). Then my automation re-applied the target state and it was actually propagated to the cloud, but it shouldn’t have taken as long as 6 minutes.

If my assumptions are correct (not a given), I can think of two solutions:

* Ideally, an operation (such as a schedule change) that resulted in an `InvalidAuth` error and a token refresh would be immediately reapplied after the token refresh succeeded.
* Less than ideal but still OK-ish and probably easier to implement, a full resynchronisation between all local Hypervolt entities and the cloud would be triggered following a token refresh. This way, an automation like mine that compared the current state with the target state every minute would take corrective action sooner than later.

**Comment by gndean** [comment]
Thanks for the detail. That all makes sense.
Ideally we'd let Home Assistant deal with the token refreshing and that's the long term plan but it needs some help from Hypervolt so requires some coordination.
In the meantime, I've added some logic to proactively refresh the access token before it expires. This should keep the integration logged in at all times. In think that also addresses the valid point about the `InvalidAuth` error - now it should be a genuine error.
See release V2.3.2
