### ISSUE TITLE
Error with set schedule service. 

### ISSUE THREAD

**Issue by Trickytree1984** [gndean/home-assistant-hypervolt-charger#69]
I get the following error when trying to run the set schedule service...

Error: expected str, bytes or os.PathLike object, not NoneType

Config is like so:
![image](https://github.com/user-attachments/assets/5f0db7ce-ebb7-4233-bab7-8bf8c5337d8c)

![image](https://github.com/user-attachments/assets/2cd09628-cc3b-425d-9e3c-9cd74ee36421)

error
![image](https://github.com/user-attachments/assets/dee0e21b-3047-4f55-81b4-c79b1accc622)

Current state of target rate sensor in octopus integration:
![image](https://github.com/user-attachments/assets/ec77f6ea-7ecb-4a33-9299-c350a3753335)

**Comment by martinpelant** [comment]
Probably same issue as https://github.com/gndean/home-assistant-hypervolt-charger/issues/66 Until fix is ready you should be able to replace it yourself locally <img width="1064" alt="Screenshot 2024-08-21 at 4 18 47 PM" src="https://github.com/user-attachments/assets/f4b0655f-2869-4642-a885-a9e7df9d57c9">

**Comment by Trickytree1984** [comment]
> Probably same issue as #66 Until fix is ready you should be able to replace it yourself locally <img alt="Screenshot 2024-08-21 at 4 18 47 PM" width="1064" src="https://private-user-images.githubusercontent.com/398815/359977001-f4b0655f-2869-4642-a885-a9e7df9d57c9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ5MjU1NjAsIm5iZiI6MTcyNDkyNTI2MCwicGF0aCI6Ii8zOTg4MTUvMzU5OTc3MDAxLWY0YjA2NTVmLTI4NjktNDY0Mi1hODg1LWE5ZTdkZjlkNTdjOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyOVQwOTU0MjBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYjFhYTIwYjgxYWI4M2Q2ZjA1NWIyOTA4NWI3ZTI3MWQ3MTVlZDhjZDRiNjAwMmE3ZGE2N2I4ZGQ5N2I2YmFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.UDdES1wRFC6UuyYtfO7DaDmEx4aAkoAhJIYGpObtxkA">

Thanks for this. I changed the variable above but still get the same error. Looking deeper into the logs this is the error:

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:525
First occurred: 11:09:17 (2 occurrences)
Last logged: 11:12:53

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: expected str, bytes or os.PathLike object, not NoneType
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 525, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 764, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 727, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2763, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2806, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/hypervolt_charger/service.py", line 56, in async_set_schedule
    timezone = get_time_zone(coordinator.data.schedule_tz)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/dt.py", line 105, in get_time_zone
    return zoneinfo.ZoneInfo(time_zone_str)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/zoneinfo/_tzpath.py", line 73, in find_tzfile
    _validate_tzfile_path(key)
  File "/usr/local/lib/python3.12/zoneinfo/_tzpath.py", line 86, in _validate_tzfile_path
    if os.path.isabs(path):
       ^^^^^^^^^^^^^^^^^^^
  File "<frozen posixpath>", line 62, in isabs
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by Meatballs1** [comment]
What version of HA are  you on?
What version of the integration are you on?
What charger have you got?
What timezone are you in/what is the charger set to?

I'm not seeing this issue with 2024.5 and v2.3.2 and a v2 charger in BST/UK.

It looks like it stems from:

timezone = get_time_zone(coordinator.data.schedule_tz)


Have you ever setup a schedule before? I wonder if it may be Null if you have never used oone, so maybe set one up in the app first.

**Comment by Trickytree1984** [comment]
Hi i still have the issue. 

HA versions

Core 2024.9.3
Supervisor 2024.09.1
Operating System 13.1
Frontend 20240909.1

Hypervolt V3 charger

Hypervolt integration version: 2.3.2

I have set a scheduled in in the past, there is one set on the charger at the moment (from when i had last set it for negative agile rates)

![image](https://github.com/user-attachments/assets/34e7c7e2-6ea1-475e-9fff-294a8ae62edc)

**Comment by Trickytree1984** [comment]
Looking in the settings on the hypervolt app, timezone is set to Europe/London

**Comment by Meatballs1** [comment]
Could try the following fix: https://github.com/Meatballs1/home-assistant-hypervolt-charger/blob/timezone_workaround/custom_components/hypervolt_charger/service.py

I've not tested it yet
```
                        try:
                            timezone = get_time_zone(coordinator.data.schedule_tz)
                        except Exception:
                            timezone = get_time_zone("Europe/London")
```
