### ISSUE TITLE
Websocket Errors:  "Detected blocking call to load_default_certs" and "cannot send"

### ISSUE THREAD

**Issue by giuliodali** [gndean/home-assistant-hypervolt-charger#72]
Hi,

This is appearing in my logs when some automations failed:

`2024-09-09 22:03:33.069 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to load_default_certs with args (<ssl.SSLContext object at 0x7fba70cba550>, <Purpose.SERVER_AUTH: _ASN1Object(nid=129, shortname='serverAuth', longname='TLS Web Server Authentication', oid='1.3.6.1.5.5.7.3.1')>) inside the event loop by custom integration 'hypervolt_charger' at custom_components/hypervolt_charger/hypervolt_api_client.py, line 405: async for websocket in websockets.connect( (offender: /usr/local/lib/python3.12/ssl.py, line 713: context.load_default_certs(purpose)), please create a bug report at https://github.com/gndean/home-assistant-hypervolt-charger/issues
For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#load_default_certs
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
    sys.exit(main())
  File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
    exit_code = runner.run(runtime_conf)
  File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run
    return loop.run_until_complete(setup_and_run_hass(runtime_config))
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever
    self._run_once()
  File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once
    handle._run()
  File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 288, in notify_on_hypervolt_sync_websocket
    await self.notify_on_websocket(
  File "/config/custom_components/hypervolt_charger/hypervolt_api_client.py", line 405, in notify_on_websocket
    async for websocket in websockets.connect(
`

Followed by a bunch of these:

`
2024-09-10 20:07:47.530 WARNING (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-199, ConnectionClosedError, code: 1006, reason: 
2024-09-10 20:07:51.026 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync cannot send because websocket_sync is not set
2024-09-10 20:07:51.031 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync cannot send because websocket_sync is not set

2024-09-10 23:30:09.886 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync cannot send because websocket_sync is not set
2024-09-10 23:30:09.890 ERROR (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] Send_message_to_sync cannot send because websocket_sync is not set
2024-09-11 00:44:41.927 WARNING (MainThread) [homeassistant.helpers.entity] Update of sensor.solismodbus_inverter_status is taking over 10 seconds

2024-09-11 01:03:00.220 WARNING (MainThread) [custom_components.hypervolt_charger.hypervolt_api_client] notify_on_websocket sync, Task-199, ConnectionClosedError, code: 1006, reason: 

`

Thanks,

Giulio

**Comment by gndean** [comment]
Fixed in 2.4.1
